spring:
  config:
    import: optional:classpath:env.production.yml
  datasource:
    url: ${app.database.url}
    username: ${app.database.username}
    password: ${app.database.password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      "[hibernate.format_sql]": true
    open-in-view: false

  servlet.multipart:
    max-file-size: 20MB
    max-request-size: 20MB
    location: ${java.io.tmpdir}

  jackson:
    default-property-inclusion: non-null
          
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
