spring:
  profiles:
    active: staging
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server.servlet:
  context-path: /
