version: "2.2"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: es01
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  esdata01:
    driver: local
